version: "3"
services:
  web:
    build:
      context: ./src
    ports:
      - "5000:5000"
    env_file: web.env
    depends_on:
      - "db"
  db:
    image: postgres:latest
    env_file: db.env
    ports:
      - "5432:5432"